# Generated by Django 5.1.1 on 2024-10-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_orderbasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
